<template>
  <div>
    <button @click="sendSMS">Send SMS</button>
  </div>
</template>

<script>
export default {
  methods: {
    sendSMS() {
      const phoneNumber = '+639358403712'; 
      const message = 'Good day! There is a pending HRSI form that needs your attention. This is an autogenerated message.';

      
      const accountSid = 'ACc482a44e914ba27f3af09bab31fc6e4c';
      const authToken = 'f95b99ed53499e65ef6b21297cdeff70';

      
      fetch(`https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
          Authorization: 'Basic ' + btoa(`${accountSid}:${authToken}`),
        },
        body: new URLSearchParams({
          To: phoneNumber,
          From: '+1254 4420867', // Replace with your Twilio phone number
          Body: message,
        }),
      })
        .then((response) => {
          if (response.ok) {
            console.log('SMS sent successfully!');
          } else {
            console.error('Failed to send SMS:', response.statusText);
          }
        })
        .catch((error) => {
          console.error('Error sending SMS:', error);
        });
    },
  },
};
</script>
